% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Jan-2016 14:13:58
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

Orientation = saveVarsMat.Orientation; % <1x1 timeseries> unsupported class

clear saveVarsMat;
